---
name: PaymentPool
main: blugin\api\paymentpool\PaymentPool
version: 1.0.0
api: [3.0.0]
authors: ['Blugin-team', 'PresentKim']
description: '[API] API plugin that registers and manages several payment plugins'
depend: ['libCommand']
load: STARTUP

permissions:
  payment.cmd:
    description: PaymentPool command
    default: op
    children:
      payment.cmd.set:
        description: PaymentPool command - set
        default: op
      payment.cmd.links:
        description: PaymentPool command - links
        default: op
      payment.cmd.list:
        description: PaymentPool command - list
        default: op
...
